### ISSUE TITLE
Threat/Risk: Further normalization of SMS delivery for one-time PINs.

### ISSUE THREAD

**Issue by mhardeman** [WebKit/explainers#10]
Nothing in this proposal addresses hijacking of SMS message delivery.  There are numerous mechanisms, well documented elsewhere, for hijacking SMS messages at both the network and endpoint layers.

This proposal, in formalizing standards and mechanisms for transferring the one-time-pin payload of a message into the browser/app in which the user must authenticate, would seem to be a vote in further normalizing and advocating SMS as a legitimate mechanism for one-time-pin authentication.

**Comment by othermaciej** [comment]
The intent of this proposal is harm reduction. It doesn't solve the SMS delivery hijacking risk. But it does reduce the phishing risk.

**Comment by mhardeman** [comment]
I would concur that presuming certain implementation details, there may be a net reduction in phishing risk.  I also understand that it's possible that some of those implementation details may not yet be documented or that interested parties may not wish to document them as yet.

However, I put forth that a mechanism in which the SMS message is still human readable and may be read by the user with the OTP in the clear still presents a phishing risk which doesn't seem to be mitigated by the proposal.

**Comment by othermaciej** [comment]
I think your other issue on that specific topic (hiding message from visibility along with normal SMS messages) is a good suggestions.

**Comment by rmondello** [comment]
> However, I put forth that a mechanism in which the SMS message is still human readable and may be read by the user with the OTP in the clear still presents a phishing risk which doesn't seem to be mitigated by the proposal.

The scope of the proposal is a way for websites/service providers/relying parties (depending on which terminology you prefer) to:
- Make their one-time code messages origin-bound on platforms/browsers that understand the concept
- Makes their one-time code messages understood to be one-time code messages
- Clearly state the code that such a message contains

You’re correct that the proposal doesn’t cover how the origin-bound one-time codes could or should be presented to users in the context of a message transcript. This is explicitly an area for implementers to reason about, and is not covered by the proposal. Issue #9 helpfully has some great suggestions to consider in this area.

**Comment by mhardeman** [comment]
> * Clearly state the code that such a message contains

One aspect of this scope/requirement I'd like to make sure that I understand is whether by "Clearly state the code..." it is a requirement that the code be human readable in the plain text form?

**Comment by rmondello** [comment]
> One aspect of this scope/requirement I'd like to make sure that I understand is whether by "Clearly state the code..." it is a requirement that the code be human readable in the plain text form?

That itself is interesting and worth discussing. Would you mind raising another issue for this? (Unless it’s already covered by another issue.)

**Comment by mhardeman** [comment]
> That itself is interesting and worth discussing. Would you mind raising another issue for this? (Unless it’s already covered by another issue.)

Issue #12 concerns the underlying reasons I wish to further understand if it's necessary to express the OTP code in human readable form.  If preserving the OTP in human readable form is an essential requirement, my proposal in #12 is not useful to incorporate.  If providing clear text of the OTP is not essential, perhaps something of what I have discussed in #12 may be useful.

**Comment by hober** [comment]
Thank you so much for raising this issue. It looks to me like #9 and #12 are appropriate followups given this conversation, so I'm going to close this issue. Please open a new issue if #9 and #12 don't fully capture your remaining concerns here.
