### ISSUE TITLE
Recommendation/Request: Document an illustrative best-practice implement of UA interaction

### ISSUE THREAD

**Issue by mhardeman** [WebKit/explainers#11]
In an effort to permit the community to better assess the security properties of the proposal, might I recommend that the proposal be expanded to incorporate a series of mocked-up user interface interactions across the variety of software components or applications of an abstract user operating environment?  In other words, what the messaging application receives, displays to the user, causes to occur?  What the reliant software be it browser or other application receives and upon what trigger?

This would help to answer questions such as whether or not the user's device attempts to thwart copy-paste or read and type of a one-time PIN delivered in this mechanism.

**Comment by hober** [comment]
I think screenshots / mockups could definitely help understanding, but aren't strictly necessary to convey the substance of the proposal. I've marked this issue 'editorial' and am leaving it open.

**Comment by reillyeon** [comment]
This explainer is based on a collaboration with @samuelgoto. His [explainer](https://github.com/samuelgoto/WebOTP/blob/master/explainer.md) for Chromium's version of this proposal includes animations of a number of different UX flows for this type of interaction and a discussion of the alternatives considered.

**Comment by hober** [comment]
This proposal has been taken up in the @wicg, where you can find an updated [explainer](https://github.com/wicg/sms-one-time-codes) as well as a [spec](https://wicg.github.io/sms-one-time-codes/). If, after reviewing the spec, you still have concerns on this topic, please [file an issue](https://github.com/wicg/sms-one-time-codes/issues/new) in the spec's dedicated repo.
