### ISSUE TITLE
Consideration of other payload formats?

### ISSUE THREAD

**Issue by mhardeman** [WebKit/explainers#12]
Was consideration given to, or would consideration be given to, alternative mechanisms for formatting the one-time PIN delivery payload?

For example, if a relying party wished to enforce support of an origin respecting mechanism such as that proposed here, perhaps the first authentication message they send obfuscates the origin and PIN in a mechanism a person could not easily decode by hand.

By way of example, such a message might look like:

ServiceName one-time PIN message.  This message requires iOS x.y.y+ or Android VooDooDonut Z+.  See https://authinfo.sms for more info. base_64_blurb_here_contains OTP:origin.com:OTP_PIN_HERE.

**Comment by rmondello** [comment]
Consideration will be given to feedback given in good faith that’s relevant to the proposal! Your feedback across several issues has been thoughtful and helpful, so I’m happy to discuss this.

What you’re proposing here is interesting, but adds different value (and potentially solves different problems) than what this proposal is putting forward. I think the destiny of this feedback is to be taken to a different proposal or venue, but while we’re here, could you be explicit about what you’re trying to achieve with such an obfuscation scheme? I can take guesses, but would prefer not to.

**Comment by mhardeman** [comment]
I'm happy to pitch in, if I may contribute anything useful.  If I stray from the useful, by all means let me know.

If I hear that the first and principle goal in the proposal being discussed is to aid in the prevention of OTP credential leaking by way of alternate origin phishing, my first concern is whether the user even has immediate possession of the OTP token so that they could manually give it away.

In a scheme not human readable and which has a fairly rigid structure, the messaging application could literally chose not to allow copy paste and yet if a WebKit page with an appropriate origin matching the unobfuscated and parsed message content provides an OTP value for the target origin, this could be passed from the messaging app to WebKit (or potentially other consumers) securely and without the user ever having know the numeric value.

On the other hand, if I see a user in possession of an OTP value even if the OS and messaging app refuse to paste it into the clever phishing site the user is convinced needs to receive the code, I think a great many of those users will copy-paste that value and/or type it from memory.

I envision a flow where in the first instance, an adopting website sends an initial SMS OTP message that has a human readable header explaining "You should see this, click here if you do for what to do next." followed by a machine readable obfuscated blurb that contains some structured data -- an origin and OTP code at a minimum.

The website prompting for the OTP code (which is expecting to shortly receive an OTP code by this feature's automation, assuming the device software implement's the proposal's functionality) might also have a secondary, "Did your device not understand that SMS, click here to send another a 'legacy' OTP code to your device..."

**Comment by rmondello** [comment]
> In a scheme not human readable and which has a fairly rigid structure, the messaging application could literally chose not to allow copy paste and yet if a WebKit page with an appropriate origin matching the unobfuscated and parsed message content provides an OTP value for the target origin, this could be passed from the messaging app to WebKit (or potentially other consumers) securely and without the user ever having know the numeric value.

Without commenting on whether it’s a good idea, I believe that this is possible with what’s already in the explainer — the current proposed format.

I’m going to close this because I think it’s adequately covered, but if you think we should add a note to the explainer pointing out that this is a possible use of the origin-bound one-time codes, please let us know!
