### ISSUE TITLE
On Advancing an altogether different approach

### ISSUE THREAD

**Issue by mhardeman** [WebKit/explainers#13]
While I'm virtually certain this may be the wrong place to advance this request, I'm submitting this issue regardless.  I'm sure other parties can choose the applicability and merits and dispose of this appropriately.

In as far as work in the proposed area advances and furthers usability aspects of SMS OTP, my concern is that this further legitimizes a known inadequate mechanism.

FIDO2/WebAuthn would get a LOT more adoption if it didn't absolutely require a further token.

In the example of the Apple device ecosystem, both all modern macOS devices and all modern iOS devices have a sufficiently capable isolated secure element to perform the various cryptographic challenges for FIDO/WebAuthn.

Creating a built in secure-element backed virtual token which is always available to WebKit on those devices would overnight create a massive installed base of users capable of authenticating with a strong cryptographic assertion in an origin bound way.

Presumably there are many Android environments which could similarly offer this functionality.

Wouldn't advancing such capabilities combined with encouraging authentication platforms to implement WebAuthn and especially to support multiple registered credentials to any user principle who needs to authenticate be the better way to advance secure authentication on the web?

**Comment by othermaciej** [comment]
This feature request for Safari/WebKit on iOS and macOS is off topic here. 

For what it's worth, we have implemented an experimental feature for exposing a platform authenticator via WebAuthN on macOS and iOS. We have a [public bug tracking this](https://bugs.webkit.org/show_bug.cgi?id=206967) in the WebKit bug tracker. Comments there are welcome.

We think it's worth improving SMS codes even with that feature.

This should probably be closed as off topic but I'll let the explainer editors decide that.

**Comment by mhardeman** [comment]
This is a reasonable position and I don't object presuming an actual anti-phishing risk mitigation provided by the ultimate proposal.

**Comment by hober** [comment]
Closing per the conversation above. Thanks!
