### ISSUE TITLE
Goals section is not clear

### ISSUE THREAD

**Issue by othermaciej** [WebKit/explainers#15]
The goals section is a little muddy. I think a more succinct version of the goals would be:

- Allow video publishers to continue storing captions in legacy or custom formats
- Make sure users can control presence and style of captions with system accessibility settings

As a result, we have this derived goal:
- Allow captions to be served in custom formats, but still be rendered by the browser engine

The current goals as stated are met by the existence of WebVTT, I think. It's only the combo of these two goals that requires a new thing.

**Comment by othermaciej** [comment]
I can provide a PR to that effect if folks agree.

**Comment by hober** [comment]
I agree, and will write a PR for it. Thanks!
