### ISSUE TITLE
Expand introduction to clarify the scope of this proposal

### ISSUE THREAD

**Issue by aaronpk** [WebKit/explainers#18]
Regarding https://github.com/WebKit/explainers/blob/master/sms-one-time-code-format/README.md

There are many problems with delivering one-time codes via SMS, so I was very curious to see which of these this proposal is tackling. It was not immediately obvious from the Introduction and Goal sections which specific piece this is attempting to solve.

I would appreciate some additional text clarifying the scope of this, so that a reader doesn't go into this expecting it to, for example, solve SMS code phishing. I think two things could help clarify this proposal:

* describing the user experience that implementing this proposal will provide to end users
* describing who is expected to implement this proposal (website owners? mobile phone vendors?)

**Comment by hober** [comment]
I think this is a fair point; the introduction could definitely help clarify this. I'll try to get a PR up soon to address this.

(Marking 'editorial' because this doesn't change any conformance requirements.)

**Comment by hober** [comment]
Resolved by #23. Please let me know if you think this needs more tweaking.
