### ISSUE TITLE
Threat/Risk: 2FA bypass

### ISSUE THREAD

**Issue by jrmoserbaltimore** [WebKit/explainers#19]
The proposal as written suggests a user will not have to copy or type the OTP code into a Web site, and that the system will programmatically deliver the code to the Web site.

Upon receiving such a code, the code is delivered to validate the authentication.  It seems to me any log-in will thus immediately receive the correct OTP, and thus will validate.  The second factor is then "is your phone on?"

**Comment by mhardeman** [comment]
That's not my understanding.  My understanding would be that there's a browser open to a particular site (origin) and in the process of logging into a particular account.  As part of that process, the OTP code is SMS texted to the number on record for the user.
When the device receives the code, and identifies that it is tagged for that particular origin and a page with that origin is open and has an input element with the attribute tagging it for OTP auto completion, then the OTP value is copied over into the field.

So, the second factor is being able to receive an OTP code at a particular previously known telephone number, during the login process, and when the browser is open to a page from the bound origin and that page has a field with the attribute indicating autocompletion of OTP should happen.

**Comment by rmondello** [comment]
> The proposal as written suggests a user will not have to copy or type the OTP code into a Web site, and that the system will programmatically deliver the code to the Web site.

The proposal as written states that users shouldn’t have to copy and paste codes. To say that “the system will programmatically deliver the code to the Web site” is reading too far into the text of the proposal, and not understanding its scope. The proposal is about service providers being able to bind one-time codes to an origin. User agents/platforms can respect that binding however they see fit, after thoughtfully considering what would be user-beneficial.

> Upon receiving such a code, the code is delivered to validate the authentication. It seems to me any log-in will thus immediately receive the correct OTP, and thus will validate. The second factor is then "is your phone on?”

There is no basis for this assumption based on the proposal. The proposal states that the origin-binding determines where codes can be used, and has nothing to say the manner they will be used, and what user consent model is defined for how they will be used.

**Comment by hober** [comment]
Closing based on the above discussion.
