### ISSUE TITLE
SMS Messaging and Newlines / Line breaks

### ISSUE THREAD

**Issue by mhardeman** [WebKit/explainers#22]
A consequence of the SMS market being so diverse both in terms of endpoints and their interpretation and presentation of messages along with a diverse marketplace of APIs and interfaces for a non-mobile device to originate SMS messages has yielded a circumstance in which expressing the intent of a "new line", "carriage return", "line break", etc. is ambiguous both as to what the API / messaging gateway expects to see as well as what the final byte-stream that goes to the device's messaging application will be and also sometimes how that device's messaging application will in turn actually interpret that byte-stream.

While I don't wish to further diminish the rules for specifically matching a pattern to identify that this is an OTP autocomplete message, I feel it is prudent to mention that specifying that the @origin.com segment starts on a new line means a lot of different things on a lot of different platforms and just as many different things when you're trying to originate an SMS message on a non-mobile device.

This was once a far larger issue, and it's not nearly as bad as it once was.  Having said that, it remains less than ideal.

You should also consider that there's a whole parallel message format delivered with the same addressing type (and similar routing) to SMS -- MMS -- and that a non-mobile-originated MMS message might end up containing the OTP autocomplete payload instead of an SMS.  If this should occur, that line break might actually be an HTML tag.

A google search such as `sms message "line break"` may be informative on this issue.

**Comment by hober** [comment]
The spec, when written, should rely on the [Infra Standard](https://infra.spec.whatwg.org/) for handling this kind of thing (see e.g. the definition of [normalize newlines](https://infra.spec.whatwg.org/#normalize-newlines) in that spec), which should unambiguously handle such variance.

The proposal is only about SMS, not MMS. How to parse such a message out of MMS would indeed be more challenging to spec.
