### ISSUE TITLE
Should specify how to handle IDN hostnames

### ISSUE THREAD

**Issue by hartman** [WebKit/explainers#26]
This should probably specify how to handle IDN hostnames..

I'm assuming IDNA encoded, but it is always good to make something like that explicit.

**Comment by hartman** [comment]
@rmondello and @hober 
sorry, created this one-time-code issue, but had to log in during that process and that seems to have caused GitHub to loose my create template flow. please label approriately

**Comment by hober** [comment]
The spec should definitely say how to handle IDNs. I don't think we need to cover this in the explainer, though.
