### ISSUE TITLE
GSM vs ascii encoding mismatches

### ISSUE THREAD

**Issue by hartman** [WebKit/explainers#27]
Has anyone considered any spoofing implications of character encoding mismatches ?

Like what if I have a hostname using a character that is within the ascii charset, but not in the GSM charset (or gsm extended) and then an operator introduces a characters conversion error by (incorrectly) converting the message from the 'unicode' set to the gsm encoding set ?

I don't think this is a terrible issue btw., but it might be good to consider the impact of the ancient parts of the technology used, just to make sure that it isn't a problem.

**Comment by hober** [comment]
We should probably cover such a concern in the Security Considerations section of the eventual spec.  Explainers are much more high level, though, so I don't think we need to cover this in it. I've made a note to myself to capture this in the spec, whenever I write it. Thanks!
