### ISSUE TITLE
Is it secure to allow software otp to trigger an SMS otp

### ISSUE THREAD

**Issue by kimocrossman1** [WebKit/explainers#28]
If not already envisioned, enhance standard in any way required to allow software otps to generate an otp sms after authentication.

So my LastPass or Google authenticator app on my phone could also generate this otp sms.

**Comment by hober** [comment]
I'm afraid I don't understand the question. Could you elaborate? How does this relate to this proposal, which is specifically about one-time codes delivered over SMS?

**Comment by kishoreaetna** [comment]
As I interpret the suggestion from kimocrossman1, he/she wants to extend the  "origin-bound one-time codes over SMS" proposal to authenticator apps like Google Authenticator.

Interesting idea, though probably not directly related to this proposal.

1. User opens an authenticator app like Google Authenticator and clicks on the desired configuration.
2. Authenticator app sends an SMS in the proposed format (Origin, OTP etc.)
3.  Same flow for MFA as if the SMS were sent from a authenticated service.

**Comment by hober** [comment]
@kishoreaetna, browsers are free to use apps like Google Authenticator as a source of one-time codes for autofilling with `autocomplete=one-time-code`. This feature doesn't affect that.

**Comment by hober** [comment]
I think this issue was addressed in the above conversation. If you still have concerns on this topic, please [file an issue](https://github.com/wicg/sms-one-time-codes/issues/new) in the spec's dedicated repo.
