### ISSUE TITLE
Power-saving detection / coarser low-power insights

### ISSUE THREAD

**Issue by noamr** [WebKit/explainers#47]
As per https://webkit.org/tracking-prevention/#table-of-contents-toggle:~:text=battery, we have not implemented the battery status in WebKit due to privacy/fingerprinting concerns.

However, perhaps there is a legitimate use case for coarse power detection that may align better with the webkit project goals.

The proposal is to enable something like https://github.com/w3c/battery/issues/9 - detecting (in JS or in an HTTP header such as `Save-Data: On`) whether the user agent's device is currently in power saving mode. This is coarse enough to prevent fingerprinting, but useful enough for use cases such as giving up on certain features of the site when the battery is low.

WDYT?

**Comment by othermaciej** [comment]
This question is a little off topic for this repo. Issues are supposed to be about explainers hosted here, not about opinions on existing other specs. This is discussed on webkit-dev mailing list or WebKit slack IMO.

**Comment by noamr** [comment]
Fair enough, closing and moving to webkit-dev.
