### ISSUE TITLE
Google engagement on IsLoggedIn

### ISSUE THREAD

**Issue by pwnall** [WebKit/explainers#48]
A few folks at Google would like to collaborate on the IsLoggedIn explainer.

First off, would you be interested in our feedback? (It's perfectly fine if this isn't the right time, etc.)

If you're interested in collaborating, would you be willing to (1) add a LICENSE to this repository, or (2) move the explainer to WICG, with our support?

Thank you very much!

**Comment by johnwilander** [comment]
Hi! Thanks for filing. We proposed IsLoggedIn as a work item in Privacy CG on June 1st: https://github.com/privacycg/proposals/issues/16

As you can see, it’s pending multi implementer interest. As soon as we have that we can move it to an official repo. I would love to get going!

Also, I recently proposed a joint discussion between Privacy CG and WebAppSec WG on IsLoggedIn and related proposals: https://github.com/privacycg/proposals/issues/6#issuecomment-654501839. I’ve pinged the WebAppSec co-chairs about it and mentioned it in the most recent Privacy CG call.

**Comment by othermaciej** [comment]
We have approval to contribute to Privacy CG and we'd strongly prefer to do it there over WICG. A statement of Google support would be much appreciated and we'd love to have Google collaboration and input.

**Comment by pwnall** [comment]
I apologize for being unclear earlier! I wrote WICG because I'm used to contributing there. I think that any W3C CG works. Thank you very much for pointing me to the privacy CG proposal!

I wrote a [statement of support](https://github.com/privacycg/proposals/issues/16#issuecomment-659820103) for moving this explainer to the Privacy CG.

**Comment by hober** [comment]
> I wrote a [statement of support](https://github.com/privacycg/proposals/issues/16#issuecomment-659820103) for moving this explainer to the Privacy CG.

Thanks! We've moved IsLoggedIn [over to the PrivacyCG](https://github.com/privacycg/is-logged-in). Please [file issues](https://github.com/privacycg/is-logged-in/issues/new) on it!

**Comment by pwnall** [comment]
Thank you very much! We'll reach out with thoughts there soon!
