### ISSUE TITLE
Could you write an explainer for the HTML <model> element?

### ISSUE THREAD

**Issue by simevidas** [WebKit/explainers#55]
According to the [release motes for Safari Technology Preview 129](https://webkit.org/blog/11951/release-notes-for-safari-technology-preview-129/), it seems that Safari Preview implements a non-standard HTML `<model>` element. If this element originated in WebKit, please consider writing an explainer for it. Any information would be helpful.

**Comment by othermaciej** [comment]
We have been working on an explainer and how to publish one in the near future. Also, in case it wasn't clear, note that this is a default-off experimental feature.

**Comment by tomayac** [comment]
> Also, in case it wasn't clear, note that this is a default-off experimental feature.

The [release notes](https://webkit.org/blog/11951/release-notes-for-safari-technology-preview-129/#:~:text=Added%20support%20for%20rendering%20%3Cmodel%3E%20resources%20(r279451)) for Safari Technology Preview 129 are a bit ambiguous then:

> Added support for rendering `<model>` resources
