### ISSUE TITLE
Add glTF support for the <model> tag

### ISSUE THREAD

**Issue by UX3D-nopper** [WebKit/explainers#64]
Beside USDZ and OBJ, add glTF support.

**Comment by mrdoob** [comment]
+1

I would also suggest *not* supporting OBJ. Its design is just not GPU friendly.

**Comment by bhouston** [comment]
glTF support is a must these days.  Just like <img> tag supports jpg, png, webp, the <model> tag should support at minimum usdz, and glTF for high quality models.  Lower quality models I guess can be stl and obj.

BTW I am a very strong supporter of the <model> tag, I tweeted the reasons here: https://purple.com/blog/mattress-materials-safest-sleepers

**Comment by gsnedders** [comment]
Do you foresee anything being needed in the explainer (or future specification) for this? At the moment, there isn't per-se any support for USDZ/obj: a `source` element can be provided for any file format, and the same is true for glTF.

If this is about WebKit's implementation, please file a bug on [bugs.webkit.org](https://bugs.webkit.org).

**Comment by donmccurdy** [comment]
> Do you foresee anything being needed in the explainer (or future specification) for this?

https://github.com/WebKit/explainers/issues/67 might be a good example. Boolean `autoplay` may be ambiguous if the model contains multiple animations, which glTF models often do. Standard practice in glTF viewers is to play the first animation by default, and (ideally) provide some means of selecting others. More complex composition is possible but perhaps out of scope here.

**Comment by othermaciej** [comment]
It definitely makes sense to support features of common model formats; the explainer is otherwise intended to be format-agnostic, and specific formats are mentioned only by way of example.

**Comment by tonyparisi** [comment]
100% glTF is a must-have. How is this team deciding which formats to support natively?

**Comment by tonyparisi** [comment]
> It definitely makes sense to support features of common model formats; the explainer is otherwise intended to be format-agnostic, and specific formats are mentioned only by way of example.

Maybe so, but I think it sends a confusing message to readers that the most open format, and the most widely adopted for this use case, glTF, isn't shown in the examples. It would be very easy to add .gltf and/or .glb in the example.

**Comment by ThomasNigro** [comment]
glTF not being added in the code examples currently sends a messaging close to “we will force web developers to use either an aging (old) or competing (usd) format, since we won’t support glTF in Safari”

that’s how I read it. Would 💯 to be wrong

**Comment by grorg** [comment]
To be clear, we're not deciding which formats. Those were just example code snippets.

I'll add `glTF` and remove `obj` from the examples.

**Comment by grorg** [comment]
BTW - if someone could make a gltf version of the example USDZ file I'd be very grateful. I had one, but I can't find it at the moment.

**Comment by donmccurdy** [comment]
Thanks @grorg — I've opened https://github.com/WebKit/explainers/pull/70 with a .glb version.
