### ISSUE TITLE
Support a license attribute

### ISSUE THREAD

**Issue by mattl** [WebKit/explainers#65]
3D models may very well support reuse and embedding via a well known license (Creative Commons Attribution, GPLv2, 2 clause BSD, etc) — provide a license attribute that takes a URI pointing to the relevant SPDX license page.

**Comment by hober** [comment]
The same argument could be made for `<picture>`, `<audio>`, and `<video>`, and yet for those cases the web platform has managed without this. Is there a reason why the [rel=license microformat](http://microformats.org/wiki/rel-license) isn't enough?

**Comment by grorg** [comment]
+1 to what @hober said.

**Comment by tomayac** [comment]
Search engines like Bing, Yahoo!, or Google have general support for providing licensing information for images or video, as outlined in [Google's guidelines](https://developers.google.com/search/docs/advanced/structured-data/image-license-metadata#examples). As a type, there's even [`3DModel`](https://schema.org/3DModel).

You could provide machine-readable license information about your model as outlined in the example below (using JSON-LD, out of other options, see the [guidelines](https://developers.google.com/search/docs/advanced/structured-data/image-license-metadata#examples) for more):

```html
<script type="application/ld+json">
    {
      "@context": "https://schema.org/",
      "@type": "3DModel",
      "contentUrl": "assets/example.glb",
      "license": "https://example.com/license",
      "acquireLicensePage": "https://example.com/how-to-use-my-3dmodels"
    }
</script>
<model style="width: 400px; height: 300px">
    <source src="assets/example.glb" type="model/gltf-binary">
</model>
```
