### ISSUE TITLE
Today personalized digital marketing not seems to be possible with this <model> API.

### ISSUE THREAD

**Issue by TomDadongHu** [WebKit/explainers#71]
personalized digital marketing is a big thing today. With this <model> tag, which embed a fixed interactive 3D models on the page, just like USDZ with AR quick look, seems not possible to add personalized content to the scene.   especially doing WebAR for digital marketing purpose.

**Comment by othermaciej** [comment]
Our design intent for this is that the 3D model is presented along with the webpage itself, not like the full takeover experience of AR QuickLook. So you have the whole page for personalized content. If you mean changing aspects of the 3D model itself, we are thinking about that, both plugging in values to parameterized models, and in the future an API to alter or build the geometry and materials directly.

**Comment by grorg** [comment]
As @othermaciej said, this first version only addresses static content, so any personalisation would have to happen on the server. A future version will allow for dynamic content.

**Comment by TomDadongHu** [comment]
Thank very much,  good the know, this. very excited about the future what AR would bring to us.
