### ISSUE TITLE
Bring <model> to a community or working group for wider discussion

### ISSUE THREAD

**Issue by cabanier** [WebKit/explainers#74]
We really like the simplicity of this proposal and how it sidesteps a lot of the security concerns of mixing 3D with 2D. The high level approach unlocks a bunch of use cases and we can iterate on providing lower level access later.

Even though I personally don't mind that this issue is fleshed out in this github repo, it's likely easier if it's brought to a group that is standards oriented.
I'm unsure what working group this should go since it's a new element but I suspect that the Immersive web community group is a good start.
AFAIK the last new HTML element was <portal> and we could investigate how that went through the process.

**Comment by grorg** [comment]
Yes, we definitely want to do this. Probably the W3C Immersive Web Community Group makes the most sense.

The document we have at the moment is just an introduction to get feedback.

**Comment by mikkoh** [comment]
Has a date been set for discussion in W3C Immersive Web Community Group?

**Comment by cabanier** [comment]
I believe @AdaRoseCannon put it on the agenda for TPAC.

**Comment by grorg** [comment]
We are now proposing this work be officially taken up by the W3C Immersive Web Community Group. 

https://github.com/immersive-web/proposals/issues/72
