### ISSUE TITLE
Incorrect media type for usdz in example

### ISSUE THREAD

**Issue by spiffmon** [WebKit/explainers#76]
Hi,
  In the [HTMLModelElement example](https://github.com/WebKit/explainers/tree/main/model#the-htmlmodelelement), you provide a `type="model/vnd.usd+zip"`
However, the only mime type registered with iana for usdz is [vnd.usdz+zip](https://www.iana.org/assignments/media-types/model/vnd.usdz+zip) .

Cheers,
@spiffmon

**Comment by grorg** [comment]
Thanks! Fixed.
