### ISSUE TITLE
Video support for poster

### ISSUE THREAD

**Issue by mikkoh** [WebKit/explainers#79]
It could be argued that a Video representation of a 3D model could be a better poster than a single image. Given this could poster take a video url as an argument.

I know this opens a can of worms in regard to Video + Video Format support in browsers but is this a consideration that should be made?

**Comment by grorg** [comment]
I think this is a good suggestion. I'm not sure how best to allow this though, and maybe it should apply beyond model (possibly even to `video` - why can't a poster of a video be video?).

I suggest leaving this open until it can be migrated to the Immersive Web CG issues list.

**Comment by gsnedders** [comment]
> (possibly even to `video` - why can't a poster of a video be video?)

https://bugs.webkit.org/show_bug.cgi?id=239961 suggests they can be!
