### ISSUE TITLE
Add attribute controls to <model> element

### ISSUE THREAD

**Issue by mikkoh** [WebKit/explainers#80]
The element should have some default UI which the browser should render if a new attribute `controls` is passed. This UI could include the following:

- A progress indicator for loading
- Zoom in and zoom out buttons
- UI to allow for simplified rotation of the 3D model

Some of these UI elements could contribute to better accessibility for some users. It's likely most users would override default functionality if a Javascript API is in place however it's good to have a default.

**Comment by Malvoz** [comment]
See https://github.com/WebKit/explainers/issues/69.

**Comment by othermaciej** [comment]
Duplicate of #69
