### ISSUE TITLE
Threat/Risk: Hiding / de-prioritizing a delivered message of a non-authentication type?

### ISSUE THREAD

**Issue by mhardeman** [WebKit/explainers#9]
I'm reading between the lines in an attempt to divine some implementation details.

The same-site origin concept underlying this proposal presumably relies upon the SMS messaging application on the user's device to parse and make available the one-time PIN without otherwise showing the PIN to the user, otherwise the user might still copy-paste or manually type it into the wrong origin.  I therefore presuppose that at least some implementations might choose to identify messages which meet the proposed format at some level and suppress these from view in the usual sense.

What if a user receives a text message containing further essential payload for which the sender doesn't really want to notify the user but is required to have done so via an auditable mechanism.  That sender could end the message in the format proposed here and both suppress the message from actually making it to the user and simultaneously have produced an audit log that the user was notified at their registered point of contact.

**Comment by riking** [comment]
The messaging app could collaborate in this scheme by rendering the message along the lines of:

> _Authentication code for example.com, click to expand_

upon successful delivery to a browser. This neatly solves the audit problem ( simply click all the messages ) while preserving the user experience ( can be pre-marked read, small screen space ).

**Comment by mhardeman** [comment]
@riking So the message would only be suppressed from human user reading the OTP code if the PIN were consumed successfully by a page in the browser with the matching origin?

If so, I don't think it necessarily helps reduce phishing as the pin code remains easily available to the user.

If not, the concern that I was trying to illustrate is this:

Imagine a horrible subscription service sending a notice like this via SMS:

---Begin SMS Payload---
Reminder: your free trial of sketchdating.com is expiring in 72 hours.  It will refill for $999.99/mo.  If you wish to cancel before you are billed, contact us via our conference service with the following PIN:
@shadyconference.com #47471
---End SMS Payload---

The sketchdating.com people can prove they sent an SMS warning that you'd be billed, and if you're looking for a carriage return / line break followed by the pattern "@origin #pinhere" to flag it as a special OTP auto-fill message and hiding the details from the user, the user fails to get this important message.

On the other hand, if that didn't get hidden -- at least the human readable PIN code part -- then the PIN is as susceptible to phishing as ever it has been, unless I'm missing something.

**Comment by rmondello** [comment]
> I therefore presuppose that at least some implementations might choose to identify messages which meet the proposed format at some level and suppress these from view in the usual sense.

This is something an implementation might very plausibly want to do. Any implementation considering such a use of the origin-bound one-time code scheme should thoughtfully understand what threat they’re attempting to mitigate and think through any unintended consequences. It is a non-straightforward risk/opportunity area.

**Comment by mhardeman** [comment]
> This is something an implementation might very plausibly want to do. Any implementation considering such a use of the origin-bound one-time code scheme should thoughtfully understand what threat they’re attempting to mitigate and think through any unintended consequences. It is a non-straightforward risk/opportunity area.

As I illustrated in a comment above, it is conceivable that a bad faith actor could contrive a message purporting to deliver bad news or a warning of some form to a user and yet fulfill the proposed format of the message which might well get matched by an implementing platform and hidden from normal presentation.

In such an instance as it might be necessary to continue to provide the message in a fully human-readable form, might I suggest adding a slight change to the last line of the SMS message, after that carriage return, inserting in front of the origin a fixed value sentinel which clarifies intent and would clearly identify that any party including said value for something other than an OTP message was being disingenuous and attempting to hide their communication.
For example:

rather than the proposal's current:

"After the human-readable text both the code and the origin appear on a single line, with sigils denoting which is which."

perhaps it could be:

"After the human-readable text, a fixed sentinel value of $OTPAUTHONLYMSG$ followed by the origin and code, with sigils identifying these as in the following example:"

_Your one time code is 123456_
__
_$OTPAUTHONLYMSG$ @origin.com #123456_

**Comment by hober** [comment]
> perhaps it could be:
> 
> "After the human-readable text, a fixed sentinel value of $OTPAUTHONLYMSG$ followed by the origin and code, with sigils identifying these as in the following example:"
> 
> _Your one time code is 123456_
> _$OTPAUTHONLYMSG$ @origin.com #123456_
> 
> The intention underlying such a sentinel value would be to make further explicit the match pattern upon which a messaging application vendor might utilize to flag a particular received message for special handling for use as an origin limited OTP code, which might trigger populating the OTP code into the target page/application and which further might suppress the message altogether from the normal messaging view.

I don't think this is necessary. If and when people generate a specification from this explainer, the parsing rules will be well-defined, much like with other Web interchange formats. As is, the rules in the explainer are unambiguous, so I don't think such a sentinel is necessary.

**Comment by mhardeman** [comment]
> I don't think this is necessary. If and when people generate a specification from this explainer, the parsing rules will be well-defined, much like with other Web interchange formats. As is, the rules in the explainer are unambiguous, so I don't think such a sentinel is necessary.

I'm advocating for this because I believe that the specificity and selectivity of the proposed message format will largely determine what will be possible in terms of specifying UI behaviors later.

A regular expression as simple as "\n@.+ #[0-9]+$" is, to my opinion, too broad and ambiguous to rely upon for making a UI behavior change in which the agency granted to the user is reduced, but reduction of the user's agency to use the contents of the message when matched might very well be a legitimate goal of this mechanism.  Something substantively more explicit would not require, but would open the door to such changes.

**Comment by StoneCypher** [comment]
At this time one out of five of your issues are "hey, this isn't safe, don't do this"

In my issue #10, which you closed without commuting the significant added information, and then linked to a different closed issue, [I gave concrete examples of a mechanism like this in active use to compromise large numbers of real world Android devices](https://thenextweb.com/security/2019/09/04/hackers-are-now-attacking-android-users-with-advanced-sms-phishing-techniques/).

I would like to urge you to take more seriously the possibility that the concept is inherently flawed.  You have many non-SMS options that are more trustworthy.

**Comment by hober** [comment]
> A regular expression as simple as "\n@.+ #[0-9]+$" is, to my opinion, too broad and ambiguous 

When I write the specification, I will define how to parse the one-time code and the origin out of a given message. The parser will be precisely defined for any input string, with appropriate error handling etc. spelled out. The spec will not define this in terms of a regular expression.

I don't think it's appropriate to provide this level of detail in the explainer, though.
